<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <AtasInstallDir Condition="'$(AtasInstallDir)' == ''">C:\Program Files (x86)\ATAS Platform</AtasInstallDir>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="ATAS.Indicators">
      <HintPath>$(AtasInstallDir)\ATAS.Indicators.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="ATAS.DataFeedsCore">
      <HintPath>$(AtasInstallDir)\ATAS.DataFeedsCore.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
